[[redirects]]
  from = "/cc"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cc/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://catalogo-carola.netlify.app/admin.html"
  to = "https://admin.calzadocarola.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://catalogo-carola.netlify.app/admin"
  to = "https://admin.calzadocarola.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://calzadocarola.com/admin.html"
  to = "https://admin.calzadocarola.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://calzadocarola.com/admin"
  to = "https://admin.calzadocarola.com/"
  status = 301
  force = true

[images]
  remote_images = ['https://gfkjdpuhbxfwajbkzfap\\.supabase\\.co/storage/v1/object/public/Productos/.*']


[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
